apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: oijq1on7l-go 
  janus-idp.io/tekton: oijq1on7l-go
  backstage.io/kubernetes-id: oijq1on7l-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oijq1on7l-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml